apiVersion: v2
name: kevent-gateway
description: API gateway for kevent inference jobs
type: application
version: 0.5.12
appVersion: "v0.5.0"

dependencies:
  - name: redis-ha
    version: "4.35.10"
    repository: "https://dandydeveloper.github.io/charts"
