apiVersion: v2
name: kevent-gateway
description: API gateway for kevent inference jobs
type: application
version: 0.6.3
appVersion: "v0.6.2"

dependencies:
  - name: redis-ha
    version: "4.35.10"
    repository: "https://dandydeveloper.github.io/charts"
