{{- if not .Values.s3.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kevent-gateway.fullname" . }}-s3
  labels:
    {{- include "kevent-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | quote }}
{{- end }}
{{- if and .Values.kafka.sasl.enabled (not .Values.kafka.sasl.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kevent-gateway.fullname" . }}-kafka
  labels:
    {{- include "kevent-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_SASL_PASSWORD: {{ .Values.kafka.sasl.password | quote }}
{{- end }}
{{- if and .Values.encryption.key (not .Values.encryption.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kevent-gateway.fullname" . }}-encryption
  labels:
    {{- include "kevent-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENCRYPTION_KEY: {{ .Values.encryption.key | quote }}
{{- end }}
